#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AugmentInfo_PersonalShields

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AugmentInfo_PersonalShields.AugmentInfo_PersonalShields_C
// 0x0000 (0x0100 - 0x0100)
class UAugmentInfo_PersonalShields_C final : public UAugmentInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AugmentInfo_PersonalShields_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AugmentInfo_PersonalShields_C")
	}
	static class UAugmentInfo_PersonalShields_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAugmentInfo_PersonalShields_C>();
	}
};
DUMPER7_ASSERTS_UAugmentInfo_PersonalShields_C;

}

