#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BlinkPack

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BlinkPack.BP_BlinkPack_C
// 0x0000 (0x0288 - 0x0288)
class ABP_BlinkPack_C final : public AMABackpack
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BlinkPack_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BlinkPack_C")
	}
	static class ABP_BlinkPack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BlinkPack_C>();
	}
};
DUMPER7_ASSERTS_ABP_BlinkPack_C;

}

