#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BaseCharacter

#include "Basic.hpp"

#include "BP_BaseCharacter_classes.hpp"
#include "BP_BaseCharacter_parameters.hpp"


namespace SDK
{

// Function BP_BaseCharacter.BP_BaseCharacter_C.ExecuteUbergraph_BP_BaseCharacter
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseCharacter_C::ExecuteUbergraph_BP_BaseCharacter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "ExecuteUbergraph_BP_BaseCharacter");

	Params::BP_BaseCharacter_C_ExecuteUbergraph_BP_BaseCharacter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.BndEvt__BP_BaseCharacter_Radial_Wheel_AC_K2Node_ComponentBoundEvent_3_On Selection Changed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const struct FRadial_Wheel_Slot_Struct& Selected_Slot                                          (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool                                    Valid_                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BaseCharacter_C::BndEvt__BP_BaseCharacter_Radial_Wheel_AC_K2Node_ComponentBoundEvent_3_On_Selection_Changed__DelegateSignature(const struct FRadial_Wheel_Slot_Struct& Selected_Slot, bool Valid_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "BndEvt__BP_BaseCharacter_Radial_Wheel_AC_K2Node_ComponentBoundEvent_3_On Selection Changed__DelegateSignature");

	Params::BP_BaseCharacter_C_BndEvt__BP_BaseCharacter_Radial_Wheel_AC_K2Node_ComponentBoundEvent_3_On_Selection_Changed__DelegateSignature Parms{};

	Parms.Selected_Slot = std::move(Selected_Slot);
	Parms.Valid_ = Valid_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.BndEvt__BP_BaseCharacter_Radial_Wheel_AC_K2Node_ComponentBoundEvent_1_On Wheel Closed__DelegateSignature
// (BlueprintEvent)

void ABP_BaseCharacter_C::BndEvt__BP_BaseCharacter_Radial_Wheel_AC_K2Node_ComponentBoundEvent_1_On_Wheel_Closed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "BndEvt__BP_BaseCharacter_Radial_Wheel_AC_K2Node_ComponentBoundEvent_1_On Wheel Closed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.HideEmoteWheel
// (Event, Public, BlueprintEvent)

void ABP_BaseCharacter_C::HideEmoteWheel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "HideEmoteWheel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.ShowEmoteWheel
// (Event, Public, BlueprintEvent)

void ABP_BaseCharacter_C::ShowEmoteWheel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "ShowEmoteWheel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BaseCharacter_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.K2_OnMovementModeChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// EMovementMode                           PrevMovementMode                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EMovementMode                           NewMovementMode                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   PrevCustomMode                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   NewCustomMode                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseCharacter_C::K2_OnMovementModeChanged(EMovementMode PrevMovementMode, EMovementMode NewMovementMode, uint8 PrevCustomMode, uint8 NewCustomMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "K2_OnMovementModeChanged");

	Params::BP_BaseCharacter_C_K2_OnMovementModeChanged Parms{};

	Parms.PrevMovementMode = PrevMovementMode;
	Parms.NewMovementMode = NewMovementMode;
	Parms.PrevCustomMode = PrevCustomMode;
	Parms.NewCustomMode = NewCustomMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.BP_OnRep_PlayerState
// (Event, Public, BlueprintEvent)

void ABP_BaseCharacter_C::BP_OnRep_PlayerState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "BP_OnRep_PlayerState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.BP_PlayTakeHitEffects
// (BlueprintCallable, BlueprintEvent)

void ABP_BaseCharacter_C::BP_PlayTakeHitEffects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "BP_PlayTakeHitEffects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseCharacter_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "ReceiveTick");

	Params::BP_BaseCharacter_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void ABP_BaseCharacter_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void ABP_BaseCharacter_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_BaseCharacter_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_BaseCharacter_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BaseCharacter_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.GetWeaponByIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   WeaponIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AMAWeapon**                       Weapon_0                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseCharacter_C::GetWeaponByIndex(int32 WeaponIndex, class AMAWeapon** Weapon_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "GetWeaponByIndex");

	Params::BP_BaseCharacter_C_GetWeaponByIndex Parms{};

	Parms.WeaponIndex = WeaponIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (Weapon_0 != nullptr)
		*Weapon_0 = Parms.Weapon_0;
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.Zoomed
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    isZoomed                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BaseCharacter_C::Zoomed(bool isZoomed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "Zoomed");

	Params::BP_BaseCharacter_C_Zoomed Parms{};

	Parms.isZoomed = isZoomed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseCharacter.BP_BaseCharacter_C.GetOriginalGravityScale
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Enabled                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float*                                  GravityScale                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseCharacter_C::GetOriginalGravityScale(bool* Enabled, float* GravityScale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseCharacter_C", "GetOriginalGravityScale");

	Params::BP_BaseCharacter_C_GetOriginalGravityScale Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Enabled != nullptr)
		*Enabled = Parms.Enabled;

	if (GravityScale != nullptr)
		*GravityScale = Parms.GravityScale;
}

}

