#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChaingunAmmoArt

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ChaingunAmmoArt.BP_ChaingunAmmoArt_C
// 0x0000 (0x02B8 - 0x02B8)
class ABP_ChaingunAmmoArt_C final : public AWeaponAmmoArt
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ChaingunAmmoArt_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ChaingunAmmoArt_C")
	}
	static class ABP_ChaingunAmmoArt_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ChaingunAmmoArt_C>();
	}
};
DUMPER7_ASSERTS_ABP_ChaingunAmmoArt_C;

}

