#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChaingunAttachment

#include "Basic.hpp"

#include "BP_ChaingunAttachment_classes.hpp"
#include "BP_ChaingunAttachment_parameters.hpp"


namespace SDK
{

// Function BP_ChaingunAttachment.BP_ChaingunAttachment_C.ExecuteUbergraph_BP_ChaingunAttachment
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ChaingunAttachment_C::ExecuteUbergraph_BP_ChaingunAttachment(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChaingunAttachment_C", "ExecuteUbergraph_BP_ChaingunAttachment");

	Params::BP_ChaingunAttachment_C_ExecuteUbergraph_BP_ChaingunAttachment Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ChaingunAttachment.BP_ChaingunAttachment_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ChaingunAttachment_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChaingunAttachment_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ChaingunAttachment.BP_ChaingunAttachment_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ChaingunAttachment_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChaingunAttachment_C", "ReceiveTick");

	Params::BP_ChaingunAttachment_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

