#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FragGrenade_Shell

#include "Basic.hpp"

#include "BP_FragGrenade_Shell_classes.hpp"
#include "BP_FragGrenade_Shell_parameters.hpp"


namespace SDK
{

// Function BP_FragGrenade_Shell.BP_FragGrenade_Shell_C.ExecuteUbergraph_BP_FragGrenade_Shell
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FragGrenade_Shell_C::ExecuteUbergraph_BP_FragGrenade_Shell(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_Shell_C", "ExecuteUbergraph_BP_FragGrenade_Shell");

	Params::BP_FragGrenade_Shell_C_ExecuteUbergraph_BP_FragGrenade_Shell Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FragGrenade_Shell.BP_FragGrenade_Shell_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FragGrenade_Shell_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FragGrenade_Shell_C", "ReceiveEndPlay");

	Params::BP_FragGrenade_Shell_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}

}

