#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GalacticLeopard39

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GalacticLeopard39.BP_GalacticLeopard39_C
// 0x0018 (0x0240 - 0x0228)
class ABP_GalacticLeopard39_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Main;                                              // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Parts;                                             // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        SharedRoot;                                        // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GalacticLeopard39_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GalacticLeopard39_C")
	}
	static class ABP_GalacticLeopard39_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GalacticLeopard39_C>();
	}
};
DUMPER7_ASSERTS_ABP_GalacticLeopard39_C;

}

