#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LightCharacter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_BaseCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LightCharacter.BP_LightCharacter_C
// 0x0010 (0x0B60 - 0x0B50)
class ABP_LightCharacter_C final : public ABP_BaseCharacter_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_LightCharacter_C;                // 0x0B48(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               JetTrailMain;                                      // 0x0B50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         jetstrength;                                       // 0x0B58(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SpawnRate_0_0;                                     // 0x0B5C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_LightCharacter(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void BP_UpdateForClientPerspective(bool bFirstPerson);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LightCharacter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LightCharacter_C")
	}
	static class ABP_LightCharacter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LightCharacter_C>();
	}
};
DUMPER7_ASSERTS_ABP_LightCharacter_C;

}

