#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Patience

#include "Basic.hpp"

#include "BP_Patience_classes.hpp"
#include "BP_Patience_parameters.hpp"


namespace SDK
{

// Function BP_Patience.BP_Patience_C.GetCurrentEnergyChangeRate
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UBP_Patience_C::GetCurrentEnergyChangeRate() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Patience_C", "GetCurrentEnergyChangeRate");

	Params::BP_Patience_C_GetCurrentEnergyChangeRate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

