#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Railgun_Bolt

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_Railgun_Bolt.BP_Railgun_Bolt_C.ExecuteUbergraph_BP_Railgun_Bolt
// 0x0010 (0x0010 - 0x0000)
struct BP_Railgun_Bolt_C_ExecuteUbergraph_BP_Railgun_Bolt final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Railgun_Bolt_C_ExecuteUbergraph_BP_Railgun_Bolt;

// Function BP_Railgun_Bolt.BP_Railgun_Bolt_C.UserConstructionScript
// 0x000C (0x000C - 0x0000)
struct BP_Railgun_Bolt_C_UserConstructionScript final
{
public:
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Railgun_Bolt_C_UserConstructionScript;

}

