#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ramp

#include "Basic.hpp"

#include "BP_Ramp_classes.hpp"
#include "BP_Ramp_parameters.hpp"


namespace SDK
{

// Function BP_Ramp.BP_Ramp_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Ramp_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ramp_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

