#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_GrappleHookCharacter

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_GrappleHookCharacter.BPI_GrappleHookCharacter_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_GrappleHookCharacter_C final
{
public:
	void OnProjectileHitAnySurface(bool IsValid, bool IsCharacter, const struct FHitResult& Hit);
	void OnProjectileCloseToGrapplePoint();
	void OnProjectileExpires();
	void OnProjectileMaxDistanceBroken();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_GrappleHookCharacter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_GrappleHookCharacter_C")
	}
	static class IBPI_GrappleHookCharacter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_GrappleHookCharacter_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_GrappleHookCharacter_C;

}

