#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_UI_Interface

#include "Basic.hpp"

#include "BPI_UI_Interface_classes.hpp"
#include "BPI_UI_Interface_parameters.hpp"


namespace SDK
{

// Function BPI_UI_Interface.BPI_UI_Interface_C.StackRef
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_Menu_C*                       Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_UI_Interface_C::StackRef(class UBP_Menu_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_UI_Interface_C", "StackRef");

	Params::BPI_UI_Interface_C_StackRef Parms{};

	Parms.Widget = Widget;

	AsUObject()->ProcessEvent(Func, &Parms);
}

}

