#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CSkin_DefaultSetup

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CSkin_DefaultSetup.CSkin_DefaultSetup_C
// 0x0010 (0x0290 - 0x0280)
class ACSkin_DefaultSetup_C : public ASkinConfiguration
{
public:
	class USpotLightComponent*                    SpotLight;                                         // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCameraComponent*                       Camera;                                            // 0x0288(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CSkin_DefaultSetup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CSkin_DefaultSetup_C")
	}
	static class ACSkin_DefaultSetup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACSkin_DefaultSetup_C>();
	}
};
DUMPER7_ASSERTS_ACSkin_DefaultSetup_C;

}

