#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DmgType_Blaster

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DmgType_Blaster.DmgType_Blaster_C
// 0x0000 (0x00B0 - 0x00B0)
class UDmgType_Blaster_C final : public UMADamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DmgType_Blaster_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DmgType_Blaster_C")
	}
	static class UDmgType_Blaster_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDmgType_Blaster_C>();
	}
};
DUMPER7_ASSERTS_UDmgType_Blaster_C;

}

