#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JSkin_Default

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass JSkin_Default.JSkin_Default_C
// 0x0008 (0x02C8 - 0x02C0)
class AJSkin_Default_C : public AParticleConfiguration
{
public:
	class UCameraComponent*                       Camera;                                            // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("JSkin_Default_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JSkin_Default_C")
	}
	static class AJSkin_Default_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AJSkin_Default_C>();
	}
};
DUMPER7_ASSERTS_AJSkin_Default_C;

}

