#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JSkin_BlazeRed

#include "Basic.hpp"

#include "JSkin_Default_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass JSkin_BlazeRed.JSkin_BlazeRed_C
// 0x0000 (0x02C8 - 0x02C8)
class AJSkin_BlazeRed_C final : public AJSkin_Default_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("JSkin_BlazeRed_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JSkin_BlazeRed_C")
	}
	static class AJSkin_BlazeRed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AJSkin_BlazeRed_C>();
	}
};
DUMPER7_ASSERTS_AJSkin_BlazeRed_C;

}

