#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Male_ABP_LightCharacter_3P

#include "Basic.hpp"

#include "RetargettedABP_Character_3P_New_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Male_ABP_LightCharacter_3P.Male_ABP_LightCharacter_3P_C
// 0x0000 (0x83D0 - 0x83D0)
class UMale_ABP_LightCharacter_3P_C final : public URetargettedABP_Character_3P_New_C
{
public:
	void Get_Weapon_Scale(class AMAWeaponAttachment* Weapon, float* Weapon_Scale);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Male_ABP_LightCharacter_3P_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Male_ABP_LightCharacter_3P_C")
	}
	static class UMale_ABP_LightCharacter_3P_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMale_ABP_LightCharacter_3P_C>();
	}
};
DUMPER7_ASSERTS_UMale_ABP_LightCharacter_3P_C;

}

