#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ManaExtractor_Middle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ManaExtractor_Middle.ManaExtractor_Middle_C
// 0x0020 (0x0248 - 0x0228)
class AManaExtractor_Middle_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class URotatingMovementComponent*             RotatingMovement;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_ManaExtractor_Middle;                           // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ManaExtractor_Middle(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ManaExtractor_Middle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaExtractor_Middle_C")
	}
	static class AManaExtractor_Middle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AManaExtractor_Middle_C>();
	}
};
DUMPER7_ASSERTS_AManaExtractor_Middle_C;

}

