#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RabbitFlag

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RabbitFlag.RabbitFlag_C
// 0x0010 (0x0560 - 0x0550)
class ARabbitFlag_C final : public AMACTFFlag
{
public:
	class UAudioComponent*                        IdleLoopSound;                                     // 0x0550(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RabbitFlag_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RabbitFlag_C")
	}
	static class ARabbitFlag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARabbitFlag_C>();
	}
};
DUMPER7_ASSERTS_ARabbitFlag_C;

}

