#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TeamRabbitFlag

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TeamRabbitFlag.TeamRabbitFlag_C
// 0x0010 (0x0590 - 0x0580)
class ATeamRabbitFlag_C final : public AMALeagueFlag
{
public:
	class UAudioComponent*                        IdleLoopSound;                                     // 0x0580(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TeamRabbitFlag_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TeamRabbitFlag_C")
	}
	static class ATeamRabbitFlag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATeamRabbitFlag_C>();
	}
};
DUMPER7_ASSERTS_ATeamRabbitFlag_C;

}

