#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VoiceSetInfo_Male_B

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VoiceSetInfo_Male_B.VoiceSetInfo_Male_B_C
// 0x0000 (0x0108 - 0x0108)
class UVoiceSetInfo_Male_B_C final : public UVoiceSetInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VoiceSetInfo_Male_B_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VoiceSetInfo_Male_B_C")
	}
	static class UVoiceSetInfo_Male_B_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVoiceSetInfo_Male_B_C>();
	}
};
DUMPER7_ASSERTS_UVoiceSetInfo_Male_B_C;

}

