#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ConfirmationDialog

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Midair2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_ConfirmationDialog.W_ConfirmationDialog_C
// 0x0010 (0x0370 - 0x0360)
class UW_ConfirmationDialog_C : public UMAConfirmationScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0360(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       OnActivated;                                       // 0x0368(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_W_ConfirmationDialog(int32 EntryPoint);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_ConfirmationDialog_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_ConfirmationDialog_C")
	}
	static class UW_ConfirmationDialog_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_ConfirmationDialog_C>();
	}
};
DUMPER7_ASSERTS_UW_ConfirmationDialog_C;

}

