#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ConfirmationDialog

#include "Basic.hpp"

#include "W_ConfirmationDialog_classes.hpp"
#include "W_ConfirmationDialog_parameters.hpp"


namespace SDK
{

// Function W_ConfirmationDialog.W_ConfirmationDialog_C.ExecuteUbergraph_W_ConfirmationDialog
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ConfirmationDialog_C::ExecuteUbergraph_W_ConfirmationDialog(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ConfirmationDialog_C", "ExecuteUbergraph_W_ConfirmationDialog");

	Params::W_ConfirmationDialog_C_ExecuteUbergraph_W_ConfirmationDialog Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ConfirmationDialog.W_ConfirmationDialog_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UW_ConfirmationDialog_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ConfirmationDialog_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

