#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ServerPasswordDialog

#include "Basic.hpp"

#include "W_ServerPasswordDialog_classes.hpp"
#include "W_ServerPasswordDialog_parameters.hpp"


namespace SDK
{

// Function W_ServerPasswordDialog.W_ServerPasswordDialog_C.BndEvt__W_LobbyJoinCode_W_Midair_MenuBtn_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ServerPasswordDialog_C::BndEvt__W_LobbyJoinCode_W_Midair_MenuBtn_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerPasswordDialog_C", "BndEvt__W_LobbyJoinCode_W_Midair_MenuBtn_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::W_ServerPasswordDialog_C_BndEvt__W_LobbyJoinCode_W_Midair_MenuBtn_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerPasswordDialog.W_ServerPasswordDialog_C.BndEvt__W_LobbyJoinCode_W_Midair_MenuBtn_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ServerPasswordDialog_C::BndEvt__W_LobbyJoinCode_W_Midair_MenuBtn_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerPasswordDialog_C", "BndEvt__W_LobbyJoinCode_W_Midair_MenuBtn_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::W_ServerPasswordDialog_C_BndEvt__W_LobbyJoinCode_W_Midair_MenuBtn_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerPasswordDialog.W_ServerPasswordDialog_C.BndEvt__W_ServerPasswordDialog_ServerPasswordET_K2Node_ComponentBoundEvent_2_OnEditableTextBoxCommittedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ServerPasswordDialog_C::BndEvt__W_ServerPasswordDialog_ServerPasswordET_K2Node_ComponentBoundEvent_2_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerPasswordDialog_C", "BndEvt__W_ServerPasswordDialog_ServerPasswordET_K2Node_ComponentBoundEvent_2_OnEditableTextBoxCommittedEvent__DelegateSignature");

	Params::W_ServerPasswordDialog_C_BndEvt__W_ServerPasswordDialog_ServerPasswordET_K2Node_ComponentBoundEvent_2_OnEditableTextBoxCommittedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerPasswordDialog.W_ServerPasswordDialog_C.ExecuteUbergraph_W_ServerPasswordDialog
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ServerPasswordDialog_C::ExecuteUbergraph_W_ServerPasswordDialog(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerPasswordDialog_C", "ExecuteUbergraph_W_ServerPasswordDialog");

	Params::W_ServerPasswordDialog_C_ExecuteUbergraph_W_ServerPasswordDialog Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ServerPasswordDialog.W_ServerPasswordDialog_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UW_ServerPasswordDialog_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ServerPasswordDialog_C", "BP_GetDesiredFocusTarget");

	Params::W_ServerPasswordDialog_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

