#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SettingsListEntry_KBMBinding

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_SettingsListEntry_KBMBinding.W_SettingsListEntry_KBMBinding_C
// 0x0008 (0x0328 - 0x0320)
class UW_SettingsListEntry_KBMBinding_C final : public UMASettingsListEntrySetting_KeyboardInput
{
public:
	class USizeBox*                               EntryHeightSB;                                     // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_SettingsListEntry_KBMBinding_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_SettingsListEntry_KBMBinding_C")
	}
	static class UW_SettingsListEntry_KBMBinding_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_SettingsListEntry_KBMBinding_C>();
	}
};
DUMPER7_ASSERTS_UW_SettingsListEntry_KBMBinding_C;

}

