#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RouteTrailRow

#include "Basic.hpp"

#include "WBP_RouteTrailRow_classes.hpp"
#include "WBP_RouteTrailRow_parameters.hpp"


namespace SDK
{

// Function WBP_RouteTrailRow.WBP_RouteTrailRow_C.ExecuteUbergraph_WBP_RouteTrailRow
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RouteTrailRow_C::ExecuteUbergraph_WBP_RouteTrailRow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RouteTrailRow_C", "ExecuteUbergraph_WBP_RouteTrailRow");

	Params::WBP_RouteTrailRow_C_ExecuteUbergraph_WBP_RouteTrailRow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RouteTrailRow.WBP_RouteTrailRow_C.BndEvt__DeleteRouteTrailButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_RouteTrailRow_C::BndEvt__DeleteRouteTrailButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RouteTrailRow_C", "BndEvt__DeleteRouteTrailButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RouteTrailRow.WBP_RouteTrailRow_C.BndEvt__LoadRouteTrailButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_RouteTrailRow_C::BndEvt__LoadRouteTrailButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RouteTrailRow_C", "BndEvt__LoadRouteTrailButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RouteTrailRow.WBP_RouteTrailRow_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RouteTrailRow_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RouteTrailRow_C", "OnListItemObjectSet");

	Params::WBP_RouteTrailRow_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RouteTrailRow.WBP_RouteTrailRow_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_RouteTrailRow_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RouteTrailRow_C", "BP_OnItemSelectionChanged");

	Params::WBP_RouteTrailRow_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RouteTrailRow.WBP_RouteTrailRow_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_RouteTrailRow_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RouteTrailRow_C", "BP_OnItemExpansionChanged");

	Params::WBP_RouteTrailRow_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RouteTrailRow.WBP_RouteTrailRow_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_RouteTrailRow_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RouteTrailRow_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_RouteTrailRow.WBP_RouteTrailRow_C.SetRouteTrail
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FMARouteTrail&             RouteTrail_0                                           (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_RouteTrailRow_C::SetRouteTrail(const struct FMARouteTrail& RouteTrail_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RouteTrailRow_C", "SetRouteTrail");

	Params::WBP_RouteTrailRow_C_SetRouteTrail Parms{};

	Parms.RouteTrail_0 = std::move(RouteTrail_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_RouteTrailRow.WBP_RouteTrailRow_C.GetMAPracticeComponentForWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMAPracticeComponent**            MAPracticeComponent                                    (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_RouteTrailRow_C::GetMAPracticeComponentForWidget(class UMAPracticeComponent** MAPracticeComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_RouteTrailRow_C", "GetMAPracticeComponentForWidget");

	Params::WBP_RouteTrailRow_C_GetMAPracticeComponentForWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MAPracticeComponent != nullptr)
		*MAPracticeComponent = Parms.MAPracticeComponent;
}

}

