#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SingleStat

#include "Basic.hpp"

#include "WBP_SingleStat_classes.hpp"
#include "WBP_SingleStat_parameters.hpp"


namespace SDK
{

// Function WBP_SingleStat.WBP_SingleStat_C.ExecuteUbergraph_WBP_SingleStat
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SingleStat_C::ExecuteUbergraph_WBP_SingleStat(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SingleStat_C", "ExecuteUbergraph_WBP_SingleStat");

	Params::WBP_SingleStat_C_ExecuteUbergraph_WBP_SingleStat Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SingleStat.WBP_SingleStat_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_SingleStat_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SingleStat_C", "PreConstruct");

	Params::WBP_SingleStat_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SingleStat.WBP_SingleStat_C.SetTextSize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_SingleStat_C::SetTextSize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SingleStat_C", "SetTextSize");

	UObject::ProcessEvent(Func, nullptr);
}

}

