#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PracticeMenuComboBox_Row

#include "Basic.hpp"

#include "WBP_PracticeMenuComboBox_Row_classes.hpp"
#include "WBP_PracticeMenuComboBox_Row_parameters.hpp"


namespace SDK
{

// Function WBP_PracticeMenuComboBox_Row.WBP_PracticeMenuComboBox_Row_C.ExecuteUbergraph_WBP_PracticeMenuComboBox_Row
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PracticeMenuComboBox_Row_C::ExecuteUbergraph_WBP_PracticeMenuComboBox_Row(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PracticeMenuComboBox_Row_C", "ExecuteUbergraph_WBP_PracticeMenuComboBox_Row");

	Params::WBP_PracticeMenuComboBox_Row_C_ExecuteUbergraph_WBP_PracticeMenuComboBox_Row Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PracticeMenuComboBox_Row.WBP_PracticeMenuComboBox_Row_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_PracticeMenuComboBox_Row_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PracticeMenuComboBox_Row_C", "OnMouseLeave");

	Params::WBP_PracticeMenuComboBox_Row_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PracticeMenuComboBox_Row.WBP_PracticeMenuComboBox_Row_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_PracticeMenuComboBox_Row_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PracticeMenuComboBox_Row_C", "OnMouseEnter");

	Params::WBP_PracticeMenuComboBox_Row_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PracticeMenuComboBox_Row.WBP_PracticeMenuComboBox_Row_C.Get_TextBlock_Option_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PracticeMenuComboBox_Row_C::Get_TextBlock_Option_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PracticeMenuComboBox_Row_C", "Get_TextBlock_Option_Text_0");

	Params::WBP_PracticeMenuComboBox_Row_C_Get_TextBlock_Option_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

