#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ComboItem

#include "Basic.hpp"

#include "WBP_ComboItem_classes.hpp"
#include "WBP_ComboItem_parameters.hpp"


namespace SDK
{

// Function WBP_ComboItem.WBP_ComboItem_C.ExecuteUbergraph_WBP_ComboItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ComboItem_C::ExecuteUbergraph_WBP_ComboItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComboItem_C", "ExecuteUbergraph_WBP_ComboItem");

	Params::WBP_ComboItem_C_ExecuteUbergraph_WBP_ComboItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComboItem.WBP_ComboItem_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ComboItem_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComboItem_C", "OnMouseEnter");

	Params::WBP_ComboItem_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ComboItem.WBP_ComboItem_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ComboItem_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ComboItem_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

