#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ScoreboardSlot

#include "Basic.hpp"

#include "WBP_ScoreboardSlot_classes.hpp"
#include "WBP_ScoreboardSlot_parameters.hpp"


namespace SDK
{

// Function WBP_ScoreboardSlot.WBP_ScoreboardSlot_C.ExecuteUbergraph_WBP_ScoreboardSlot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ScoreboardSlot_C::ExecuteUbergraph_WBP_ScoreboardSlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSlot_C", "ExecuteUbergraph_WBP_ScoreboardSlot");

	Params::WBP_ScoreboardSlot_C_ExecuteUbergraph_WBP_ScoreboardSlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ScoreboardSlot.WBP_ScoreboardSlot_C.BndEvt__WBP_ScoreboardSlot_Button_216_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_ScoreboardSlot_C::BndEvt__WBP_ScoreboardSlot_Button_216_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSlot_C", "BndEvt__WBP_ScoreboardSlot_Button_216_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ScoreboardSlot.WBP_ScoreboardSlot_C.BndEvt__BTN_DropdownOptions_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_ScoreboardSlot_C::BndEvt__BTN_DropdownOptions_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSlot_C", "BndEvt__BTN_DropdownOptions_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ScoreboardSlot.WBP_ScoreboardSlot_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ScoreboardSlot_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSlot_C", "Tick");

	Params::WBP_ScoreboardSlot_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ScoreboardSlot.WBP_ScoreboardSlot_C.Update Info (New)
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       Icon                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   rank                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AMAPlayerState*                   Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Team                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Friendly                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_ScoreboardSlot_C::Update_Info__New_(class UTexture2D* Icon, int32 rank, class AMAPlayerState* Player, int32 Team, bool Friendly)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSlot_C", "Update Info (New)");

	Params::WBP_ScoreboardSlot_C_Update_Info__New_ Parms{};

	Parms.Icon = Icon;
	Parms.rank = rank;
	Parms.Player = Player;
	Parms.Team = Team;
	Parms.Friendly = Friendly;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ScoreboardSlot.WBP_ScoreboardSlot_C.Get_BG_BrushColor_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_ScoreboardSlot_C::Get_BG_BrushColor_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSlot_C", "Get_BG_BrushColor_0");

	Params::WBP_ScoreboardSlot_C_Get_BG_BrushColor_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_ScoreboardSlot.WBP_ScoreboardSlot_C.SetBG_Opacity
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ScoreboardSlot_C::SetBG_Opacity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSlot_C", "SetBG_Opacity");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ScoreboardSlot.WBP_ScoreboardSlot_C.GetBackground_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UWBP_ScoreboardSlot_C::GetBackground_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSlot_C", "GetBackground_0");

	Params::WBP_ScoreboardSlot_C_GetBackground_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_ScoreboardSlot.WBP_ScoreboardSlot_C.Get Voice Icon
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UWBP_ScoreboardSlot_C::Get_Voice_Icon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSlot_C", "Get Voice Icon");

	Params::WBP_ScoreboardSlot_C_Get_Voice_Icon Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

