#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ScoreboardSpectatorList

#include "Basic.hpp"

#include "WBP_ScoreboardSpectatorList_classes.hpp"
#include "WBP_ScoreboardSpectatorList_parameters.hpp"


namespace SDK
{

// Function WBP_ScoreboardSpectatorList.WBP_ScoreboardSpectatorList_C.ExecuteUbergraph_WBP_ScoreboardSpectatorList
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ScoreboardSpectatorList_C::ExecuteUbergraph_WBP_ScoreboardSpectatorList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSpectatorList_C", "ExecuteUbergraph_WBP_ScoreboardSpectatorList");

	Params::WBP_ScoreboardSpectatorList_C_ExecuteUbergraph_WBP_ScoreboardSpectatorList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ScoreboardSpectatorList.WBP_ScoreboardSpectatorList_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ScoreboardSpectatorList_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSpectatorList_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ScoreboardSpectatorList.WBP_ScoreboardSpectatorList_C.Slow Tick
// (BlueprintCallable, BlueprintEvent)

void UWBP_ScoreboardSpectatorList_C::Slow_Tick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSpectatorList_C", "Slow Tick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ScoreboardSpectatorList.WBP_ScoreboardSpectatorList_C.UpdateVBoxWithPlayers
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class AMAPlayerState*>&          players                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ScoreboardSpectatorList_C::UpdateVBoxWithPlayers(TArray<class AMAPlayerState*>& players)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSpectatorList_C", "UpdateVBoxWithPlayers");

	Params::WBP_ScoreboardSpectatorList_C_UpdateVBoxWithPlayers Parms{};

	Parms.players = std::move(players);

	UObject::ProcessEvent(Func, &Parms);

	players = std::move(Parms.players);
}


// Function WBP_ScoreboardSpectatorList.WBP_ScoreboardSpectatorList_C.Get_Status_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_ScoreboardSpectatorList_C::Get_Status_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSpectatorList_C", "Get_Status_Text_0");

	Params::WBP_ScoreboardSpectatorList_C_Get_Status_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_ScoreboardSpectatorList.WBP_ScoreboardSpectatorList_C.Get_Team_Score_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_ScoreboardSpectatorList_C::Get_Team_Score_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSpectatorList_C", "Get_Team_Score_0");

	Params::WBP_ScoreboardSpectatorList_C_Get_Team_Score_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_ScoreboardSpectatorList.WBP_ScoreboardSpectatorList_C.Get_Team_Color
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_ScoreboardSpectatorList_C::Get_Team_Color()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSpectatorList_C", "Get_Team_Color");

	Params::WBP_ScoreboardSpectatorList_C_Get_Team_Color Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_ScoreboardSpectatorList.WBP_ScoreboardSpectatorList_C.Set_Team_Icon
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamId_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ScoreboardSpectatorList_C::Set_Team_Icon(int32 TeamId_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScoreboardSpectatorList_C", "Set_Team_Icon");

	Params::WBP_ScoreboardSpectatorList_C_Set_Team_Icon Parms{};

	Parms.TeamId_0 = TeamId_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

