#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Speedometer_HorizontalBar

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Speedometer_HorizontalBar.WBP_Speedometer_HorizontalBar_C
// 0x0020 (0x0280 - 0x0260)
class UWBP_Speedometer_HorizontalBar_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_ExtendedProgressBar_C*              BP_ExtendedProgressBar;                            // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_0;                                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         Speed;                                             // 0x0278(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Speedometer_HorizontalBar(int32 EntryPoint);
	void CustomEvent_0();
	void SlowTick();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Speedometer_HorizontalBar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Speedometer_HorizontalBar_C")
	}
	static class UWBP_Speedometer_HorizontalBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Speedometer_HorizontalBar_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Speedometer_HorizontalBar_C;

}

