#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EndOfMatch

#include "Basic.hpp"

#include "WBP_EndOfMatch_classes.hpp"
#include "WBP_EndOfMatch_parameters.hpp"


namespace SDK
{

// Function WBP_EndOfMatch.WBP_EndOfMatch_C.ExecuteUbergraph_WBP_EndOfMatch
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void WBP_EndOfMatch::UWBP_EndOfMatch_C::ExecuteUbergraph_WBP_EndOfMatch(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndOfMatch_C", "ExecuteUbergraph_WBP_EndOfMatch");

	Params::WBP_EndOfMatch_C_ExecuteUbergraph_WBP_EndOfMatch Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_EndOfMatch.WBP_EndOfMatch_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void WBP_EndOfMatch::UWBP_EndOfMatch_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndOfMatch_C", "Tick");

	Params::WBP_EndOfMatch_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_EndOfMatch.WBP_EndOfMatch_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void WBP_EndOfMatch::UWBP_EndOfMatch_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndOfMatch_C", "PreConstruct");

	Params::WBP_EndOfMatch_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_EndOfMatch.WBP_EndOfMatch_C.Get_BG_Image_Brush_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush WBP_EndOfMatch::UWBP_EndOfMatch_C::Get_BG_Image_Brush_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndOfMatch_C", "Get_BG_Image_Brush_0");

	Params::WBP_EndOfMatch_C_Get_BG_Image_Brush_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_EndOfMatch.WBP_EndOfMatch_C.TempStatGenerator
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void WBP_EndOfMatch::UWBP_EndOfMatch_C::TempStatGenerator()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndOfMatch_C", "TempStatGenerator");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EndOfMatch.WBP_EndOfMatch_C.UpdateTeamScore
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void WBP_EndOfMatch::UWBP_EndOfMatch_C::UpdateTeamScore()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndOfMatch_C", "UpdateTeamScore");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EndOfMatch.WBP_EndOfMatch_C.UpdateCurrentLevelName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void WBP_EndOfMatch::UWBP_EndOfMatch_C::UpdateCurrentLevelName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndOfMatch_C", "UpdateCurrentLevelName");

	UObject::ProcessEvent(Func, nullptr);
}

}

