#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TabRoute

#include "Basic.hpp"

#include "WBP_TabRoute_classes.hpp"
#include "WBP_TabRoute_parameters.hpp"


namespace SDK
{

// Function WBP_TabRoute.WBP_TabRoute_C.ExecuteUbergraph_WBP_TabRoute
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TabRoute_C::ExecuteUbergraph_WBP_TabRoute(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "ExecuteUbergraph_WBP_TabRoute");

	Params::WBP_TabRoute_C_ExecuteUbergraph_WBP_TabRoute Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TabRoute.WBP_TabRoute_C.BndEvt__WBP_TabRoute_WBP_DifficultySelector_K2Node_ComponentBoundEvent_3_DifficultySelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// ERouteTrailDifficulty                   Difficulty                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TabRoute_C::BndEvt__WBP_TabRoute_WBP_DifficultySelector_K2Node_ComponentBoundEvent_3_DifficultySelected__DelegateSignature(ERouteTrailDifficulty Difficulty)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "BndEvt__WBP_TabRoute_WBP_DifficultySelector_K2Node_ComponentBoundEvent_3_DifficultySelected__DelegateSignature");

	Params::WBP_TabRoute_C_BndEvt__WBP_TabRoute_WBP_DifficultySelector_K2Node_ComponentBoundEvent_3_DifficultySelected__DelegateSignature Parms{};

	Parms.Difficulty = Difficulty;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TabRoute.WBP_TabRoute_C.BndEvt__WBP_TabRoute_WBP_RouteTypeSelector_K2Node_ComponentBoundEvent_2_RouteTypeSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    RouteType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_TabRoute_C::BndEvt__WBP_TabRoute_WBP_RouteTypeSelector_K2Node_ComponentBoundEvent_2_RouteTypeSelected__DelegateSignature(const class FString& RouteType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "BndEvt__WBP_TabRoute_WBP_RouteTypeSelector_K2Node_ComponentBoundEvent_2_RouteTypeSelected__DelegateSignature");

	Params::WBP_TabRoute_C_BndEvt__WBP_TabRoute_WBP_RouteTypeSelector_K2Node_ComponentBoundEvent_2_RouteTypeSelected__DelegateSignature Parms{};

	Parms.RouteType = std::move(RouteType);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TabRoute.WBP_TabRoute_C.BndEvt__WBP_TabRoute_WBP_Title_K2Node_ComponentBoundEvent_0_Title_Clicked__DelegateSignature
// (BlueprintEvent)

void UWBP_TabRoute_C::BndEvt__WBP_TabRoute_WBP_Title_K2Node_ComponentBoundEvent_0_Title_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "BndEvt__WBP_TabRoute_WBP_Title_K2Node_ComponentBoundEvent_0_Title_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TabRoute.WBP_TabRoute_C.BndEvt__WBP_TabRoute_WBP_Button_Action_K2Node_ComponentBoundEvent_1_Action_Button_Clicked__DelegateSignature
// (BlueprintEvent)

void UWBP_TabRoute_C::BndEvt__WBP_TabRoute_WBP_Button_Action_K2Node_ComponentBoundEvent_1_Action_Button_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "BndEvt__WBP_TabRoute_WBP_Button_Action_K2Node_ComponentBoundEvent_1_Action_Button_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TabRoute.WBP_TabRoute_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_TabRoute_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TabRoute.WBP_TabRoute_C.Update Route List
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_TabRoute_C::Update_Route_List()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "Update Route List");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TabRoute.WBP_TabRoute_C.GetMAPracticeComponentForWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMAPracticeComponent**            MAPracticeComponent                                    (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TabRoute_C::GetMAPracticeComponentForWidget(class UMAPracticeComponent** MAPracticeComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "GetMAPracticeComponentForWidget");

	Params::WBP_TabRoute_C_GetMAPracticeComponentForWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MAPracticeComponent != nullptr)
		*MAPracticeComponent = Parms.MAPracticeComponent;
}


// Function WBP_TabRoute.WBP_TabRoute_C.EditRouteTrail
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FMARouteTrail&             Route                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_TabRoute_C::EditRouteTrail(const struct FMARouteTrail& Route)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "EditRouteTrail");

	Params::WBP_TabRoute_C_EditRouteTrail Parms{};

	Parms.Route = std::move(Route);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TabRoute.WBP_TabRoute_C.DeleteRouteTrail
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FMARouteTrail&             Route                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_TabRoute_C::DeleteRouteTrail(const struct FMARouteTrail& Route)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "DeleteRouteTrail");

	Params::WBP_TabRoute_C_DeleteRouteTrail Parms{};

	Parms.Route = std::move(Route);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TabRoute.WBP_TabRoute_C.LoadRouteTrail
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FMARouteTrail&             Route                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_TabRoute_C::LoadRouteTrail(const struct FMARouteTrail& Route)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "LoadRouteTrail");

	Params::WBP_TabRoute_C_LoadRouteTrail Parms{};

	Parms.Route = std::move(Route);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TabRoute.WBP_TabRoute_C.SpawnBotOnRoute
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FMARouteTrail&             Route                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_TabRoute_C::SpawnBotOnRoute(const struct FMARouteTrail& Route)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabRoute_C", "SpawnBotOnRoute");

	Params::WBP_TabRoute_C_SpawnBotOnRoute Parms{};

	Parms.Route = std::move(Route);

	UObject::ProcessEvent(Func, &Parms);
}

}

