#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SelectableButtonWithText

#include "Basic.hpp"

#include "WBP_SelectableButtonWithText_classes.hpp"
#include "WBP_SelectableButtonWithText_parameters.hpp"


namespace SDK
{

// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.ExecuteUbergraph_WBP_SelectableButtonWithText
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SelectableButtonWithText_C::ExecuteUbergraph_WBP_SelectableButtonWithText(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "ExecuteUbergraph_WBP_SelectableButtonWithText");

	Params::WBP_SelectableButtonWithText_C_ExecuteUbergraph_WBP_SelectableButtonWithText Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.CustomEvent_1
// (BlueprintCallable, BlueprintEvent)

void UWBP_SelectableButtonWithText_C::CustomEvent_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "CustomEvent_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.BndEvt__DefaultButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_SelectableButtonWithText_C::BndEvt__DefaultButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "BndEvt__DefaultButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.BndEvt__DefaultButton_K2Node_ComponentBoundEvent_69_OnButtonReleasedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_SelectableButtonWithText_C::BndEvt__DefaultButton_K2Node_ComponentBoundEvent_69_OnButtonReleasedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "BndEvt__DefaultButton_K2Node_ComponentBoundEvent_69_OnButtonReleasedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.BndEvt__DefaultButton_K2Node_ComponentBoundEvent_58_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_SelectableButtonWithText_C::BndEvt__DefaultButton_K2Node_ComponentBoundEvent_58_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "BndEvt__DefaultButton_K2Node_ComponentBoundEvent_58_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.BndEvt__DefaultButton_K2Node_ComponentBoundEvent_45_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_SelectableButtonWithText_C::BndEvt__DefaultButton_K2Node_ComponentBoundEvent_45_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "BndEvt__DefaultButton_K2Node_ComponentBoundEvent_45_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.Get_DefaultBorder_BrushColor_0_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UWBP_SelectableButtonWithText_C::Get_DefaultBorder_BrushColor_0_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "Get_DefaultBorder_BrushColor_0_0");

	Params::WBP_SelectableButtonWithText_C_Get_DefaultBorder_BrushColor_0_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.Get_DefaultTextBlock_ColorAndOpacity_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor UWBP_SelectableButtonWithText_C::Get_DefaultTextBlock_ColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "Get_DefaultTextBlock_ColorAndOpacity_0");

	Params::WBP_SelectableButtonWithText_C_Get_DefaultTextBlock_ColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.Get_DefaultTextBlock_Text_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_SelectableButtonWithText_C::Get_DefaultTextBlock_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "Get_DefaultTextBlock_Text_0");

	Params::WBP_SelectableButtonWithText_C_Get_DefaultTextBlock_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_SelectableButtonWithText_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "GetVisibility_0");

	Params::WBP_SelectableButtonWithText_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.Get_NewItemBadge_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_SelectableButtonWithText_C::Get_NewItemBadge_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "Get_NewItemBadge_Visibility_0");

	Params::WBP_SelectableButtonWithText_C_Get_NewItemBadge_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.UpdateSlotAnchor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 InPosition                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 InSize                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SelectableButtonWithText_C::UpdateSlotAnchor(class UWidget* Item, const struct FVector2D& InPosition, const struct FVector2D& InSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "UpdateSlotAnchor");

	Params::WBP_SelectableButtonWithText_C_UpdateSlotAnchor Parms{};

	Parms.Item = Item;
	Parms.InPosition = std::move(InPosition);
	Parms.InSize = std::move(InSize);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_SelectableButtonWithText_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "OnFocusReceived");

	Params::WBP_SelectableButtonWithText_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_SelectableButtonWithText_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_SelectableButtonWithText_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "PreConstruct");

	Params::WBP_SelectableButtonWithText_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.OnUpdateDisabled
// (BlueprintCallable, BlueprintEvent)

void UWBP_SelectableButtonWithText_C::OnUpdateDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "OnUpdateDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.OnPressed
// (BlueprintCallable, BlueprintEvent)

void UWBP_SelectableButtonWithText_C::OnPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "OnPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.OnActive
// (BlueprintCallable, BlueprintEvent)

void UWBP_SelectableButtonWithText_C::OnActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "OnActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SelectableButtonWithText.WBP_SelectableButtonWithText_C.OnSelected
// (BlueprintCallable, BlueprintEvent)

void UWBP_SelectableButtonWithText_C::OnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SelectableButtonWithText_C", "OnSelected");

	UObject::ProcessEvent(Func, nullptr);
}

}

