#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GameStatus_Slot

#include "Basic.hpp"

#include "WBP_GameStatus_Slot_classes.hpp"
#include "WBP_GameStatus_Slot_parameters.hpp"


namespace SDK
{

// Function WBP_GameStatus_Slot.WBP_GameStatus_Slot_C.Get_TopPlayerHasFlagIcon_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_GameStatus_Slot_C::Get_TopPlayerHasFlagIcon_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameStatus_Slot_C", "Get_TopPlayerHasFlagIcon_Visibility_0");

	Params::WBP_GameStatus_Slot_C_Get_TopPlayerHasFlagIcon_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GameStatus_Slot.WBP_GameStatus_Slot_C.Get_TopPlayerIsLocalIcon_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_GameStatus_Slot_C::Get_TopPlayerIsLocalIcon_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameStatus_Slot_C", "Get_TopPlayerIsLocalIcon_Visibility_0");

	Params::WBP_GameStatus_Slot_C_Get_TopPlayerIsLocalIcon_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GameStatus_Slot.WBP_GameStatus_Slot_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_GameStatus_Slot_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameStatus_Slot_C", "GetVisibility_0");

	Params::WBP_GameStatus_Slot_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GameStatus_Slot.WBP_GameStatus_Slot_C.Get_ATeamScoreText_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_GameStatus_Slot_C::Get_ATeamScoreText_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameStatus_Slot_C", "Get_ATeamScoreText_Text_0");

	Params::WBP_GameStatus_Slot_C_Get_ATeamScoreText_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GameStatus_Slot.WBP_GameStatus_Slot_C.Update
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ScorePct_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    HasFlag_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsLocalPlayer_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_GameStatus_Slot_C::Update(class APlayerState* Player, float ScorePct_0, bool HasFlag_0, bool IsLocalPlayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameStatus_Slot_C", "Update");

	Params::WBP_GameStatus_Slot_C_Update Parms{};

	Parms.Player = Player;
	Parms.ScorePct_0 = ScorePct_0;
	Parms.HasFlag_0 = HasFlag_0;
	Parms.IsLocalPlayer_0 = IsLocalPlayer_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

