#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeaponInfo_Chaingun

#include "Basic.hpp"

#include "Midair2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeaponInfo_Chaingun.WeaponInfo_Chaingun_C
// 0x0000 (0x0120 - 0x0120)
class UWeaponInfo_Chaingun_C final : public UWeaponInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WeaponInfo_Chaingun_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WeaponInfo_Chaingun_C")
	}
	static class UWeaponInfo_Chaingun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWeaponInfo_Chaingun_C>();
	}
};
DUMPER7_ASSERTS_UWeaponInfo_Chaingun_C;

}

