#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WSkin_Blaster_ToyBox_Orange

#include "Basic.hpp"

#include "WSkin_GrenadeLauncher_Default_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WSkin_Blaster_ToyBox_Orange.WSkin_Blaster_ToyBox_Orange_C
// 0x0000 (0x0300 - 0x0300)
class AWSkin_Blaster_ToyBox_Orange_C final : public AWSkin_GrenadeLauncher_Default_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WSkin_Blaster_ToyBox_Orange_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WSkin_Blaster_ToyBox_Orange_C")
	}
	static class AWSkin_Blaster_ToyBox_Orange_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWSkin_Blaster_ToyBox_Orange_C>();
	}
};
DUMPER7_ASSERTS_AWSkin_Blaster_ToyBox_Orange_C;

}

